import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="s">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
    <h1 className="font-serif text-xl"></h1>
      <h1 className="text-xl font-bold">Home</h1>
    </div>
    
  );
}
